### ISSUE TITLE
AuthenticationPostListener line 49

### ISSUE THREAD

**Issue by firststars** [API-Skeletons/zf-oauth2-doctrine-identity#3]
I just test your module "zf-oauth2-doctrine-permissions-acl", but also use "mutatetablenames". There is a problem in the `\ ZF \ OAuth2 \ Doctrine \ Identity \ AuthenticationPostListener` line 49. Here is my quick and dirty solution.

`if(array_key_exists('mutatetablenames',$config['zf-oauth2-doctrine'])){
            unset($config['zf-oauth2-doctrine'] ['mutatetablenames']);
        }`

**Comment by TomHAnderson** [comment]
Hi,

Without a proper description of the problem you encountered I can't investigate it.  Please use Pull Requests for suggested changes; that's what they're there for.
